version: '3'
services:
  p4.helix: 
    build: helix-p4d
    ports:
      - 4000:1666
    tty: true
    
  jenkins.helix: 
    build: jenkins
    ports:
      - 4040:8080
    volumes:
      - ./data:/var/jenkins_home

  gcon.helix:
    build: helix-gcon
    ports:
      - 4022:22
      - 4080:80
      - 4443:443
    tty: true