version: '3'
services:
  p4: 
    build: helix-p4d
    ports:
      - 4000:1666
    tty: true
    
  jenkins: 
    build: jenkins
    ports:
      - 4040:8080
    volumes:
      - ./data:/var/jenkins_home
